#!/usr/bin/env bash
# traybar.sh — install, launch, and manage the claude-geiger Windows system-tray
# toggle from inside WSL2. The WSL2 counterpart to menubar.sh (which is macOS).
#
# Usage:
#   ./traybar.sh            install (copy to Windows) and (re)launch the tray app
#   ./traybar.sh --stop     quit the running tray app
#   ./traybar.sh --login    also start it at Windows login (drops a .vbs in Startup)
#   ./traybar.sh --logout   remove that Startup entry (does not stop the app)
#
# WSL2 only. There is no Linux notification area under WSLg, so the toggle lives
# in the *Windows* system tray (a tiny PowerShell app, geigerbar.ps1). It writes
# ~/.config/claude-geiger/enabled over the \\wsl.localhost\ share; geiger.sh
# reads that every poll, so muting is live — no Claude Code restart.
#
# The app is copied to %LOCALAPPDATA%\claude-geiger on the Windows side (running
# a .ps1 straight off the \\wsl.localhost\ share trips Windows' network-zone /
# execution-policy guard; an NTFS-local copy doesn't) and launched hidden via a
# .vbs so no console window flashes.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PS1_SRC="$SCRIPT_DIR/geigerbar.ps1"

# --- must be WSL, with Windows interop reachable ---------------------------
if ! grep -qiE 'microsoft|wsl' /proc/version 2>/dev/null; then
  echo "The system-tray toggle is WSL2-only (this doesn't look like WSL)."
  echo "On bare Linux, mute by writing 0 to ~/.config/claude-geiger/enabled."
  exit 1
fi
for tool in cmd.exe wscript.exe powershell.exe wslpath; do
  command -v "$tool" >/dev/null 2>&1 || { echo "Required tool not found: $tool"; exit 1; }
done

# --- resolve Windows-side locations (strip the CR cmd.exe appends) ---------
win_env() { cmd.exe /c "echo %$1%" 2>/dev/null | tr -d '\r'; }
LOCALAPPDATA_WIN="$(win_env LOCALAPPDATA)"
APPDATA_WIN="$(win_env APPDATA)"
[ -n "$LOCALAPPDATA_WIN" ] && [ -n "$APPDATA_WIN" ] || { echo "Couldn't read Windows env vars via cmd.exe."; exit 1; }

INSTALL_WIN="$LOCALAPPDATA_WIN\\claude-geiger"
INSTALL_WSL="$(wslpath -u "$LOCALAPPDATA_WIN")/claude-geiger"
STARTUP_WSL="$(wslpath -u "$APPDATA_WIN")/Microsoft/Windows/Start Menu/Programs/Startup"
VBS_WSL="$INSTALL_WSL/launch.vbs"
VBS_WIN="$INSTALL_WIN\\launch.vbs"

# The live mute file, as the Windows UNC path the tray app will write to.
mkdir -p "$HOME/.config/claude-geiger"
STATE_UNC="$(wslpath -w "$HOME/.config/claude-geiger/enabled")"

install_app() {
  [ -f "$PS1_SRC" ] || { echo "Missing $PS1_SRC"; exit 1; }
  mkdir -p "$INSTALL_WSL"
  cp "$PS1_SRC" "$INSTALL_WSL/geigerbar.ps1"
  # Tell the app where to write the live mute file.
  printf '%s' "$STATE_UNC" > "$INSTALL_WSL/statefile.txt"
  # Hidden launcher: window style 0 = no console flash.
  cat > "$VBS_WSL" <<VBS
' launch.vbs — start the claude-geiger tray app hidden (generated by traybar.sh).
Set sh = CreateObject("WScript.Shell")
sh.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ""$INSTALL_WIN\\geigerbar.ps1""", 0, False
VBS
  echo "Installed -> $INSTALL_WIN"
}

stop() {
  # Quit any running instance by matching its command line.
  powershell.exe -NoProfile -Command - >/dev/null 2>&1 <<'PSEOF' || true
Get-CimInstance Win32_Process |
  Where-Object { $_.CommandLine -like '*geigerbar.ps1*' } |
  ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
PSEOF
  echo "Stopped any running tray app."
}

start() {
  install_app
  stop >/dev/null 2>&1 || true
  wscript.exe "$VBS_WIN" >/dev/null 2>&1 || true
  echo "Tray app running — look for the ☢ radiation icon in the Windows system tray"
  echo "(by the clock; you may need to click the ^ to reveal hidden icons)."
  echo "Left-click toggles mute; right-click for the menu. Quit it there, or: ./traybar.sh --stop"
}

install_login() {
  install_app
  mkdir -p "$STARTUP_WSL"
  cp "$VBS_WSL" "$STARTUP_WSL/claude-geiger-tray.vbs"
  echo "Installed Startup entry — the tray app will start at Windows login."
}

remove_login() {
  if [ -f "$STARTUP_WSL/claude-geiger-tray.vbs" ]; then
    rm -f "$STARTUP_WSL/claude-geiger-tray.vbs"
    echo "Removed Startup entry."
  else
    echo "No Startup entry installed."
  fi
}

case "${1:-}" in
  --stop)   stop ;;
  --login)  install_login; start ;;
  --logout) remove_login ;;
  "")       start ;;
  *)        echo "Unknown option: $1"; echo "Use: --stop | --login | --logout (or no arg to launch)"; exit 1 ;;
esac
